/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as CartRouteImport } from './routes/cart'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as MarketRouteImport } from './routes/market'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OrganicRouteImport } from './routes/organic'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as ProvidersIdRouteImport } from './routes/providers.$id'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ServicesPostRequirementRouteImport } from './routes/services.post-requirement'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganicRoute = OrganicRouteImport.update({
  id: '/organic',
  path: '/organic',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIdRoute = ProvidersIdRouteImport.update({
  id: '/providers/$id',
  path: '/providers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPostRequirementRoute = ServicesPostRequirementRouteImport.update({
  id: '/services/post-requirement',
  path: '/services/post-requirement',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/cart': typeof CartRoute
  '/insurance': typeof InsuranceRoute
  '/jobs': typeof JobsRoute
  '/market': typeof MarketRoute
  '/onboarding': typeof OnboardingRoute
  '/organic': typeof OrganicRoute
  '/profile': typeof ProfileRoute
  '/provider': typeof ProviderRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/post-requirement': typeof ServicesPostRequirementRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/cart': typeof CartRoute
  '/insurance': typeof InsuranceRoute
  '/jobs': typeof JobsRoute
  '/market': typeof MarketRoute
  '/onboarding': typeof OnboardingRoute
  '/organic': typeof OrganicRoute
  '/profile': typeof ProfileRoute
  '/provider': typeof ProviderRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/post-requirement': typeof ServicesPostRequirementRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/cart': typeof CartRoute
  '/insurance': typeof InsuranceRoute
  '/jobs': typeof JobsRoute
  '/market': typeof MarketRoute
  '/onboarding': typeof OnboardingRoute
  '/organic': typeof OrganicRoute
  '/profile': typeof ProfileRoute
  '/provider': typeof ProviderRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/post-requirement': typeof ServicesPostRequirementRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bookings'
    | '/cart'
    | '/insurance'
    | '/jobs'
    | '/market'
    | '/onboarding'
    | '/organic'
    | '/profile'
    | '/provider'
    | '/providers/$id'
    | '/services/$slug'
    | '/services/post-requirement'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bookings'
    | '/cart'
    | '/insurance'
    | '/jobs'
    | '/market'
    | '/onboarding'
    | '/organic'
    | '/profile'
    | '/provider'
    | '/providers/$id'
    | '/services/$slug'
    | '/services/post-requirement'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bookings'
    | '/cart'
    | '/insurance'
    | '/jobs'
    | '/market'
    | '/onboarding'
    | '/organic'
    | '/profile'
    | '/provider'
    | '/providers/$id'
    | '/services/$slug'
    | '/services/post-requirement'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BookingsRoute: typeof BookingsRoute
  CartRoute: typeof CartRoute
  InsuranceRoute: typeof InsuranceRoute
  JobsRoute: typeof JobsRoute
  MarketRoute: typeof MarketRoute
  OnboardingRoute: typeof OnboardingRoute
  OrganicRoute: typeof OrganicRoute
  ProfileRoute: typeof ProfileRoute
  ProviderRoute: typeof ProviderRoute
  ProvidersIdRoute: typeof ProvidersIdRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesPostRequirementRoute: typeof ServicesPostRequirementRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organic': {
      id: '/organic'
      path: '/organic'
      fullPath: '/organic'
      preLoaderRoute: typeof OrganicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$id': {
      id: '/providers/$id'
      path: '/providers/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ProvidersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/post-requirement': {
      id: '/services/post-requirement'
      path: '/services/post-requirement'
      fullPath: '/services/post-requirement'
      preLoaderRoute: typeof ServicesPostRequirementRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BookingsRoute: BookingsRoute,
  CartRoute: CartRoute,
  InsuranceRoute: InsuranceRoute,
  JobsRoute: JobsRoute,
  MarketRoute: MarketRoute,
  OnboardingRoute: OnboardingRoute,
  OrganicRoute: OrganicRoute,
  ProfileRoute: ProfileRoute,
  ProviderRoute: ProviderRoute,
  ProvidersIdRoute: ProvidersIdRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesPostRequirementRoute: ServicesPostRequirementRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
